BEGIN;

ALTER TABLE orders ADD COLUMN status VARCHAR(50);
ALTER TABLE orders ALTER COLUMN status SET DEFAULT 'NEW';
UPDATE orders SET status = 'NEW' WHERE status IS NULL;
ALTER TABLE orders ALTER COLUMN status SET NOT NULL;

COMMIT;
